# Generated by Django 6.0.4 on 2026-04-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('madhab', models.CharField(choices=[('hanafi', 'Hanafi'), ('shafii', "Shafi'i")], default='hanafi', max_length=10)),
                ('overall_status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('questionable', 'Questionable'), ('hanafi_haram', 'Haram (Hanafi only)'), ('shafii_haram', "Haram (Shafi'i only)")], max_length=20)),
                ('ingredient_results', models.JSONField(default=list)),
                ('unknown_ingredients', models.JSONField(default=list)),
                ('ai_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('questionable', 'Questionable'), ('hanafi_haram', 'Haram (Hanafi only)'), ('shafii_haram', "Haram (Shafi'i only)")], max_length=20)),
                ('source', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
