# Generated by Django 6.0.4 on 2026-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='madhab',
            field=models.CharField(choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafii', "Shafi'i"), ('hanbali', 'Hanbali')], default='hanafi', max_length=10),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='overall_status',
            field=models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('questionable', 'Questionable'), ('hanafi_haram', 'Haram (Hanafi only)'), ('shafii_haram', "Haram (Shafi'i only)"), ('maliki_haram', 'Haram (Maliki only)'), ('hanbali_haram', 'Haram (Hanbali only)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('halal', 'Halal'), ('haram', 'Haram'), ('questionable', 'Questionable'), ('hanafi_haram', 'Haram (Hanafi only)'), ('shafii_haram', "Haram (Shafi'i only)"), ('maliki_haram', 'Haram (Maliki only)'), ('hanbali_haram', 'Haram (Hanbali only)')], max_length=20),
        ),
    ]
