# Generated by Django 6.0.4 on 2026-04-29 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommunityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('confirmed_halal_count', models.PositiveIntegerField(default=0)),
                ('found_issue_count', models.PositiveIntegerField(default=0)),
                ('not_sure_count', models.PositiveIntegerField(default=0)),
                ('community_verdict', models.CharField(default='unverified', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('vote', models.CharField(choices=[('confirmed_halal', 'Confirmed Halal'), ('found_issue', 'Found Issue'), ('not_sure', 'Not Sure')], max_length=20)),
                ('madhab', models.CharField(choices=[('hanafi', 'Hanafi'), ('maliki', 'Maliki'), ('shafii', "Shafi'i"), ('hanbali', 'Hanbali')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'barcode')},
            },
        ),
    ]
