# Generated by Django 6.0.4 on 2026-05-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_countryproduct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='countryproduct',
            name='unique_barcode_country',
        ),
        migrations.RenameIndex(
            model_name='countryproduct',
            new_name='core_countr_barcode_d2d39f_idx',
            old_name='countryproduct_barcode_cc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='countryproduct',
            unique_together={('barcode', 'country_code')},
        ),
    ]
